#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAPDT")]
public partial class PublishStatDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertSAPDT_DOCSURFHIST(SAPDT_DOCSURFHIST instance);
  partial void UpdateSAPDT_DOCSURFHIST(SAPDT_DOCSURFHIST instance);
  partial void DeleteSAPDT_DOCSURFHIST(SAPDT_DOCSURFHIST instance);
  partial void InsertSAPDT_DOCSURFSTATUS(SAPDT_DOCSURFSTATUS instance);
  partial void UpdateSAPDT_DOCSURFSTATUS(SAPDT_DOCSURFSTATUS instance);
  partial void DeleteSAPDT_DOCSURFSTATUS(SAPDT_DOCSURFSTATUS instance);
  #endregion
	
	public PublishStatDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SAPDTConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PublishStatDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PublishStatDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PublishStatDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PublishStatDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<SAPDT_DOCSURFHIST> SAPDT_DOCSURFHISTs
	{
		get
		{
			return this.GetTable<SAPDT_DOCSURFHIST>();
		}
	}
	
	public System.Data.Linq.Table<SAPDT_DOCSURFSTATUS> SAPDT_DOCSURFSTATUS
	{
		get
		{
			return this.GetTable<SAPDT_DOCSURFSTATUS>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAPDT_DOCSURFHIST")]
public partial class SAPDT_DOCSURFHIST : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _hid_docno;
	
	private string _hid_partno;
	
	private string _hid_version;
	
	private string _hid_status;
	
	private string _hid_revisionno;
	
	private System.Nullable<System.DateTime> _hid_revisiondate;
	
	private System.Nullable<System.DateTime> _hid_distributedate;
	
	private System.Nullable<System.DateTime> _hid_publisheddate;
	
	private System.Nullable<System.DateTime> _hid_receivedate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhid_docnoChanging(string value);
    partial void Onhid_docnoChanged();
    partial void Onhid_partnoChanging(string value);
    partial void Onhid_partnoChanged();
    partial void Onhid_versionChanging(string value);
    partial void Onhid_versionChanged();
    partial void Onhid_statusChanging(string value);
    partial void Onhid_statusChanged();
    partial void Onhid_revisionnoChanging(string value);
    partial void Onhid_revisionnoChanged();
    partial void Onhid_revisiondateChanging(System.Nullable<System.DateTime> value);
    partial void Onhid_revisiondateChanged();
    partial void Onhid_distributedateChanging(System.Nullable<System.DateTime> value);
    partial void Onhid_distributedateChanged();
    partial void Onhid_publisheddateChanging(System.Nullable<System.DateTime> value);
    partial void Onhid_publisheddateChanged();
    partial void Onhid_receivedateChanging(System.Nullable<System.DateTime> value);
    partial void Onhid_receivedateChanged();
    #endregion
	
	public SAPDT_DOCSURFHIST()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_docno", DbType="VarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string hid_docno
	{
		get
		{
			return this._hid_docno;
		}
		set
		{
			if ((this._hid_docno != value))
			{
				this.Onhid_docnoChanging(value);
				this.SendPropertyChanging();
				this._hid_docno = value;
				this.SendPropertyChanged("hid_docno");
				this.Onhid_docnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_partno", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string hid_partno
	{
		get
		{
			return this._hid_partno;
		}
		set
		{
			if ((this._hid_partno != value))
			{
				this.Onhid_partnoChanging(value);
				this.SendPropertyChanging();
				this._hid_partno = value;
				this.SendPropertyChanged("hid_partno");
				this.Onhid_partnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_version", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string hid_version
	{
		get
		{
			return this._hid_version;
		}
		set
		{
			if ((this._hid_version != value))
			{
				this.Onhid_versionChanging(value);
				this.SendPropertyChanging();
				this._hid_version = value;
				this.SendPropertyChanged("hid_version");
				this.Onhid_versionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_status", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
	public string hid_status
	{
		get
		{
			return this._hid_status;
		}
		set
		{
			if ((this._hid_status != value))
			{
				this.Onhid_statusChanging(value);
				this.SendPropertyChanging();
				this._hid_status = value;
				this.SendPropertyChanged("hid_status");
				this.Onhid_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_revisionno", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string hid_revisionno
	{
		get
		{
			return this._hid_revisionno;
		}
		set
		{
			if ((this._hid_revisionno != value))
			{
				this.Onhid_revisionnoChanging(value);
				this.SendPropertyChanging();
				this._hid_revisionno = value;
				this.SendPropertyChanged("hid_revisionno");
				this.Onhid_revisionnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_revisiondate", DbType="Date")]
	public System.Nullable<System.DateTime> hid_revisiondate
	{
		get
		{
			return this._hid_revisiondate;
		}
		set
		{
			if ((this._hid_revisiondate != value))
			{
				this.Onhid_revisiondateChanging(value);
				this.SendPropertyChanging();
				this._hid_revisiondate = value;
				this.SendPropertyChanged("hid_revisiondate");
				this.Onhid_revisiondateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_distributedate", DbType="Date")]
	public System.Nullable<System.DateTime> hid_distributedate
	{
		get
		{
			return this._hid_distributedate;
		}
		set
		{
			if ((this._hid_distributedate != value))
			{
				this.Onhid_distributedateChanging(value);
				this.SendPropertyChanging();
				this._hid_distributedate = value;
				this.SendPropertyChanged("hid_distributedate");
				this.Onhid_distributedateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_publisheddate", DbType="Date")]
	public System.Nullable<System.DateTime> hid_publisheddate
	{
		get
		{
			return this._hid_publisheddate;
		}
		set
		{
			if ((this._hid_publisheddate != value))
			{
				this.Onhid_publisheddateChanging(value);
				this.SendPropertyChanging();
				this._hid_publisheddate = value;
				this.SendPropertyChanged("hid_publisheddate");
				this.Onhid_publisheddateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hid_receivedate", DbType="Date")]
	public System.Nullable<System.DateTime> hid_receivedate
	{
		get
		{
			return this._hid_receivedate;
		}
		set
		{
			if ((this._hid_receivedate != value))
			{
				this.Onhid_receivedateChanging(value);
				this.SendPropertyChanging();
				this._hid_receivedate = value;
				this.SendPropertyChanged("hid_receivedate");
				this.Onhid_receivedateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAPDT_DOCSURFSTATUS")]
public partial class SAPDT_DOCSURFSTATUS : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _dms_docno;
	
	private string _dms_partno;
	
	private string _dms_version;
	
	private string _dms_status;
	
	private string _dms_revisionno;
	
	private System.Nullable<System.DateTime> _dms_revisiondate;
	
	private System.Nullable<System.DateTime> _dms_distributedate;
	
	private System.Nullable<System.DateTime> _dms_publisheddate;
	
	private System.Nullable<System.DateTime> _dms_receivedate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondms_docnoChanging(string value);
    partial void Ondms_docnoChanged();
    partial void Ondms_partnoChanging(string value);
    partial void Ondms_partnoChanged();
    partial void Ondms_versionChanging(string value);
    partial void Ondms_versionChanged();
    partial void Ondms_statusChanging(string value);
    partial void Ondms_statusChanged();
    partial void Ondms_revisionnoChanging(string value);
    partial void Ondms_revisionnoChanged();
    partial void Ondms_revisiondateChanging(System.Nullable<System.DateTime> value);
    partial void Ondms_revisiondateChanged();
    partial void Ondms_distributedateChanging(System.Nullable<System.DateTime> value);
    partial void Ondms_distributedateChanged();
    partial void Ondms_publisheddateChanging(System.Nullable<System.DateTime> value);
    partial void Ondms_publisheddateChanged();
    partial void Ondms_receivedateChanging(System.Nullable<System.DateTime> value);
    partial void Ondms_receivedateChanged();
    #endregion
	
	public SAPDT_DOCSURFSTATUS()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_docno", DbType="VarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string dms_docno
	{
		get
		{
			return this._dms_docno;
		}
		set
		{
			if ((this._dms_docno != value))
			{
				this.Ondms_docnoChanging(value);
				this.SendPropertyChanging();
				this._dms_docno = value;
				this.SendPropertyChanged("dms_docno");
				this.Ondms_docnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_partno", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string dms_partno
	{
		get
		{
			return this._dms_partno;
		}
		set
		{
			if ((this._dms_partno != value))
			{
				this.Ondms_partnoChanging(value);
				this.SendPropertyChanging();
				this._dms_partno = value;
				this.SendPropertyChanged("dms_partno");
				this.Ondms_partnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_version", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string dms_version
	{
		get
		{
			return this._dms_version;
		}
		set
		{
			if ((this._dms_version != value))
			{
				this.Ondms_versionChanging(value);
				this.SendPropertyChanging();
				this._dms_version = value;
				this.SendPropertyChanged("dms_version");
				this.Ondms_versionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_status", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
	public string dms_status
	{
		get
		{
			return this._dms_status;
		}
		set
		{
			if ((this._dms_status != value))
			{
				this.Ondms_statusChanging(value);
				this.SendPropertyChanging();
				this._dms_status = value;
				this.SendPropertyChanged("dms_status");
				this.Ondms_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_revisionno", DbType="VarChar(4)")]
	public string dms_revisionno
	{
		get
		{
			return this._dms_revisionno;
		}
		set
		{
			if ((this._dms_revisionno != value))
			{
				this.Ondms_revisionnoChanging(value);
				this.SendPropertyChanging();
				this._dms_revisionno = value;
				this.SendPropertyChanged("dms_revisionno");
				this.Ondms_revisionnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_revisiondate", DbType="Date")]
	public System.Nullable<System.DateTime> dms_revisiondate
	{
		get
		{
			return this._dms_revisiondate;
		}
		set
		{
			if ((this._dms_revisiondate != value))
			{
				this.Ondms_revisiondateChanging(value);
				this.SendPropertyChanging();
				this._dms_revisiondate = value;
				this.SendPropertyChanged("dms_revisiondate");
				this.Ondms_revisiondateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_distributedate", DbType="Date")]
	public System.Nullable<System.DateTime> dms_distributedate
	{
		get
		{
			return this._dms_distributedate;
		}
		set
		{
			if ((this._dms_distributedate != value))
			{
				this.Ondms_distributedateChanging(value);
				this.SendPropertyChanging();
				this._dms_distributedate = value;
				this.SendPropertyChanged("dms_distributedate");
				this.Ondms_distributedateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_publisheddate", DbType="Date")]
	public System.Nullable<System.DateTime> dms_publisheddate
	{
		get
		{
			return this._dms_publisheddate;
		}
		set
		{
			if ((this._dms_publisheddate != value))
			{
				this.Ondms_publisheddateChanging(value);
				this.SendPropertyChanging();
				this._dms_publisheddate = value;
				this.SendPropertyChanged("dms_publisheddate");
				this.Ondms_publisheddateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dms_receivedate", DbType="Date")]
	public System.Nullable<System.DateTime> dms_receivedate
	{
		get
		{
			return this._dms_receivedate;
		}
		set
		{
			if ((this._dms_receivedate != value))
			{
				this.Ondms_receivedateChanging(value);
				this.SendPropertyChanging();
				this._dms_receivedate = value;
				this.SendPropertyChanged("dms_receivedate");
				this.Ondms_receivedateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
